[FEATURE] 끄적 공개시간/범위 설정 기능 추가
wafflestudio/ggzz-server pull request #12
Opened 2023-05-23 15:52 UTC by leeeryboy

## 끄적 공개시간/범위 설정

### 한줄 요약

끄적 생성할때 공개시간/범위 설정 가능. 둘다 기본값은 0이고, 언제 어디서나 조회가능함을 의미합니다. 
`isViewable` 필드는 단건 조회가 일어나거나 매일 4AM에 업데이트되게끔 구현하였습니다.

### 상세 설명

[69324cb4aaff7932ef0172e9e99e21d17bc6555a]: 공개시간 설정 구현 (단위: 시간)

[bd30f22b4d0fac3f011ff191362e68dcdb627a41]: 공개범위 설정 구현 (단위: 미터)

[35326411e16885341bc93d83ef03791f751d8eb8]: Docs request field 추가

### TODO

기능 테스트

2023-05-27 03:25 UTC, Gorani9 requested changes
Entity 필드 추가를 위한 DB DDL 추가해주시고
테스트 코드 추가해주세요!

2023-05-27 10:31 UTC, leeeryboy commented
> Entity 필드 추가를 위한 DB DDL 추가해주시고 테스트 코드 추가해주세요!

테스트 코드 추가했습니다! DB DDL은 자동생성 밖에 안 써봤어서 그런데 어디에 추가해야하는건가요?
```
ALTER TABLE letter
ADD COLUMN is_viewable BOOLEAN DEFAULT TRUE,
ADD COLUMN viewable_time INT DEFAULT 0,
ADD COLUMN view_range INT DEFAULT 0;
```

2023-05-28 02:43 UTC, Gorani9 commented
아 다른 프로젝트랑 헷갈렸네요 ㅋㅋㅋ...
그래도 DB 스키마 변경 추적은 하면 좋으니까, `/scripts/sql` 디렉토리에 DDL 넣어주면 될 것 같아요~

2023-06-04 04:15 UTC, Gorani9 commented on src/main/kotlin/com/wafflestudio/ggzz/domain/letter/service/LetterService.kt
> +    }
공개시간을 구현해주신 부분을 보니, 끄적 필드에 `is_viewable`과 `viewable_time` 칼럼 2개를 추가해서,
1. 매일 새벽 4시 마다 `viewable_time`을 보고 `is_viewable` 업데이트하는 배치가 돌고
2. 끄적 조회시에도 `viewable_time`을 보고 `is_viewable`을 업데이트를 한다.
라고 이해했는데요.

제 생각은 두 칼럼의 역할이 분리되어야 한다고 생각합니다.
추후에 사용자의 의도에 따라 시간과 관계없이 끄적을 비공개할 수 있는 기능이 추가될 수 있고,
어차피 끄적을 조회할 때마다 `viewable_time`을 확인하니 뭔가 불필요한 로직이 추가되는 것 같아서요.

지금의 `getLetters`는 `viewable_time`과 관계없이 `is_viewable`만 보고 판단을 하기 때문에
공개 시간이 지난 끄적이 노출될 수도 있을 것 같네요.

`is_viewable` 필드와 배치 작업 추가는 보류하고, 어플리케이션에서 `viewable_time`으로만 판단하게끔 하는 것은 어떤가요?
끄적 조회할 때, 업데이트 연산은 최대한 지양하는 것이 좋을 듯 합니다 ㅎㅎ

추가)
cron expression이 "0 4 * * *" 이 아닌지요? ㅎㅎ
그리고 배치 업데이트는 어플리케이션의 for문을 통한 개별 쿼리를 여러번 날리는 것보다는 벌크 쿼리를 작성하는 것이 더 나을 것 같습니다.

2023-06-04 06:53 UTC, leeeryboy commented on src/main/kotlin/com/wafflestudio/ggzz/domain/letter/service/LetterService.kt
> +    }
`viewable_time` 으로만 판단하는것이 조회시 반복적인 시간 비교때문에 성능이 안 좋진  않을까? 하는 생각이 들어서 `is_viewable` 필드를 추가했었는데, 말씀해주신것을 들어보니 성능상 이점도 크지 않고 괜히 복잡도만 키우는것 같네요..ㅎ 말씀해주신것 반영해서 수정토록 하겠습니다.
+) cron expression은 https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/scheduling/support/CronExpression.html 를 참고했어요. 근데 안쓰는게 나을것 같네요😅

2023-06-04 07:56 UTC, Gorani9 commented on src/main/kotlin/com/wafflestudio/ggzz/domain/letter/service/LetterService.kt
> +    }
오.. Spring에서 CronExpression이 제가 알던 것과는 조금 다르네요. 좋은 레퍼런스 공유 감사합니다. ㅎㅎ

반복적인 시간 비교를 DB에 위임하면 성능이 조금 좋아질 수도 있을 것 같네요.

2023-06-30 07:09 UTC, Gorani9 approved these changes
좋네요~!

2023-07-03 11:07 UTC, YeonghyeonKO commented on scripts/sql/letter_schema_change_v1.sql
> +ALTER TABLE letter
@wafflestudio/ggzz-backend 
참고로 말씀드리면 dev Profile에서 사용 중인 MySQL 스키마는 아직 시운영 중이라 .sql 파일 필요 없이 ddl-auto를 create로 설정한 후 drop-create 하셔도 됩니다.

하지만 언제까지 갈아엎을 순 없으니 sql로 ddl 관리하는 시점도 논의해봐야겠네요 ㅎㅎ

2023-07-03 11:07 UTC, YeonghyeonKO commented on src/main/kotlin/com/wafflestudio/ggzz/domain/letter/service/LetterService.kt
> +            throw LetterNotCloseEnoughException(letter.viewRange)
해당 Exception의 String explanation을 보면, "... within ${letter.viewRange}"인데 맥락상 아래처럼 인자를 주는 것이 자연스럽지 않을까 합니다!

```suggestion
            throw LetterNotCloseEnoughException(distanceBetweenTwoPositionInMeter(pos, letterPos) - letter.viewRange)
```

2023-07-03 11:07 UTC, YeonghyeonKO commented on src/main/kotlin/com/wafflestudio/ggzz/domain/letter/exception/LetterNotCloseEnoughException.kt
> +    BadRequestException(LETTER_NOT_CLOSE_ENOUGH, "This letter can be viewed within ${viewRange}m.")
해당 예외를 사용하는 코드에 대한 아래 코멘트 참고

2023-07-03 11:07 UTC, YeonghyeonKO commented on src/main/kotlin/com/wafflestudio/ggzz/domain/letter/model/Letter.kt
> +        return this.viewableTime == 0 || ChronoUnit.HOURS.between(
`viewableTime == 0` 조건이 살짝 헷갈리는데, defaultValue로 0을 설정하신 까닭이 궁금합니다! 0으로 설정되고 이후 viewableTime 값이 바뀌지 않은 letter 객체는 “핀 고정”이나 “공지사항”과 같이 특정 지역에서 항상 노출되는 것으로 생각하셨나요??

2023-07-04 06:33 UTC, YeonghyeonKO requested changes

2023-07-04 06:33 UTC, YeonghyeonKO commented on build.gradle.kts
> +    testImplementation("org.mockito.kotlin:mockito-kotlin:4.1.0")
현재 시점의 최신 버전은 5.0.0인데, 혹시 3.2.0 -> 4.1.0으로 업그레이드 하신 이유와 4.1.0인 이유가 궁금합니다!

2023-07-04 07:04 UTC, leeeryboy commented on scripts/sql/letter_schema_change_v1.sql
> +ALTER TABLE letter
넵 현재는 그냥 DB 스키마 변경 기록용 입니다!

2023-07-04 07:09 UTC, leeeryboy commented on src/main/kotlin/com/wafflestudio/ggzz/domain/letter/service/LetterService.kt
> +            throw LetterNotCloseEnoughException(letter.viewRange)
제 의도는 몇 미터 더 접근해야 함이 아니고 '끄적 주변 {viewRange}미터 에서 확인 가능' 이라고 전달하고 싶었던건데, 에러 메세지가 조금 모호하면 수정하는게 좋을까요?

2023-07-04 07:18 UTC, leeeryboy commented on src/main/kotlin/com/wafflestudio/ggzz/domain/letter/model/Letter.kt
> +        return this.viewableTime == 0 || ChronoUnit.HOURS.between(
viewableTime 은 공개 시간을 의미하고, 끄적을 올리는 유저에게는 0이상의 값만을 입력가능하게끔 할 예정입니다(기획 회의에서 자세한 범위 설정 필요). 0, -1 로만 설정 가능한것은 아니고 24로 설정하면 24시간후에 지도에서 없어지거나, 클릭해도 볼 수 없는 상태를 생각했습니다. 테스트에서만 편의를 위해 임의로 -1로 설정해 1시간 전에 공개 시간이 끝난 끄적을 표현하고자 했습니다. + defaultValue 는 기획 회의에서 바뀔수도 있을것 같습니다!

2023-07-04 07:20 UTC, leeeryboy commented on build.gradle.kts
> +    testImplementation("org.mockito.kotlin:mockito-kotlin:4.1.0")
이거는 그냥 인텔리제이에서 밑줄을 그었길래 인텔리제이가 바꾸란대로,, 별다른 의도가 있는것은 아닙니다🤣

2023-07-04 14:04 UTC, YeonghyeonKO commented on src/main/kotlin/com/wafflestudio/ggzz/domain/letter/service/LetterService.kt
> +            throw LetterNotCloseEnoughException(letter.viewRange)
아하 그 의도셨군요!
그런데 보통 `LetterNotCloseEnoughException`를 사용하는 상황은 _User_ 관점에서 "**letter을 보고자 했으나 멀리 떨어져있기 때문에 볼 수 없음**"이므로, `viewRange`만을 사용하는 로직은 _Letter_ 의 관점에서 접근한 의도가 아닌가 합니다.

2023-07-04 14:07 UTC, YeonghyeonKO commented on src/main/kotlin/com/wafflestudio/ggzz/domain/letter/model/Letter.kt
> +        return this.viewableTime == 0 || ChronoUnit.HOURS.between(
viewableTime에 대해서는 제가 기획의도를 잘 파악을 못했네요. User에게 꽤나 많은 자유도가 있군요 ㅎㅎ

2023-07-04 14:07 UTC, YeonghyeonKO commented on build.gradle.kts
> +    testImplementation("org.mockito.kotlin:mockito-kotlin:4.1.0")
호오 인텔리제이는 4.1.0을 추천했나보네요 ㅋㅋㅋ

2023-07-06 01:15 UTC, leeeryboy commented on src/main/kotlin/com/wafflestudio/ggzz/domain/letter/service/LetterService.kt
> +            throw LetterNotCloseEnoughException(letter.viewRange)
말씀해주신거 반영해서 에러메세지 수정했습니다!

2023-07-10 06:44 UTC, YeonghyeonKO approved these changes

2023-07-10 08:07 UTC, merged