[Fix] 세션쿠키 -> jwt 인증 방식 변경
wafflestudio/ggzz-server pull request #2
Opened 2023-04-17 06:32 UTC by yangchanhk98

### 한줄 요약

- AuthTokenService 구현 및 jwt 기반 login 구현

### 상세 설명

[[400f3be](https://github.com/wafflestudio/nostalgia-server/commit/400f3beaf3114ccd546b41a6b626ff45fb02d66e)]: User에 refreshToken 추가
[[40bbdf8](https://github.com/wafflestudio/nostalgia-server/commit/40bbdf8f5970787d387495d8ab42f39d45faed54)]: data class AuthToken 추가
[[e8ad298](https://github.com/wafflestudio/nostalgia-server/commit/e8ad29803bc5199d3063508ae2789a287b7cb90b)]: 의존성 추가
[[ce37941](https://github.com/wafflestudio/nostalgia-server/commit/ce37941c7195d3f72f5629cbfd31be7e46b468e2)]: AuthTokenService 구현
[[461897b](https://github.com/wafflestudio/nostalgia-server/commit/461897b84e95405df03d0e6f184f7a26f5c14c11)]: UserService 에서 세션쿠키->jwt 로 인증 방식 변경

### TODO

- authToken에서 username을 추출하여 인증하는 process 구현
- 각 api에서 authToken 인증을 담당할 authInterceptor 구현

2023-04-17 12:39 UTC, Gorani9 reviewed
고생하셨습니다!
테스트 코드는 토큰 검증하는 인터셉터 구현이 완료되면 작성해도 될 것 같아요!

2023-04-17 12:39 UTC, Gorani9 commented on src/main/kotlin/com/wafflestudio/nostalgia/domain/user/service/AuthProperties.kt
> +@ConfigurationProperties("auth.jwt")
오... 이때까지 전 바로 YAML에서 String 값으로 읽어 왔었는데, 이 방식이 Type-safe 하면서 좋은 것 같네용 ㅎㅎ

2023-04-17 12:39 UTC, Gorani9 commented on src/main/kotlin/com/wafflestudio/nostalgia/domain/user/model/User.kt
> +    var refreshToken: String? = null,
혹시 리프레시 토큰을 DB에 저장하는 이유는 뭔가요? 리프레시 토큰을 이용해서 액세스 토큰을 재발급받는 코드가 없어서 의도를 잘 모르겠습니다.

2023-04-17 12:39 UTC, Gorani9 commented on src/main/kotlin/com/wafflestudio/nostalgia/domain/user/service/UserService.kt
> +        user.refreshToken = refreshToken
JPA Dirty Checking을 의도하신 것 같은데, 클래스 레벨에서 readOnly로 트랜잭션이 정의되어 있어서 메소드 레벨에서도 `@Transactional` 어노테이션이 필요한 것 같습니다!

2023-04-17 12:39 UTC, Gorani9 commented on src/main/kotlin/com/wafflestudio/nostalgia/domain/user/service/AuthTokenService.kt
> +@Transactional(readOnly = true)
`@Transactional` 어노테이션은 나중에 외부 DB 연결을 고려한 것일까요?

2023-04-17 12:39 UTC, Goraniieee commented on src/main/kotlin/com/wafflestudio/nostalgia/domain/user/service/AuthTokenService.kt
> +    }
액세스 토큰을 발급하는 코드랑 크게 다르지 않은 것 같은데, 메소드를 따로 빼는 것도 좋아보입니다

2023-04-17 12:39 UTC, Gorani9 commented on src/main/kotlin/com/wafflestudio/nostalgia/domain/user/service/AuthTokenService.kt
> +            .maxAge(3600)
maxAge(3600)으로 설정하게 되면 토큰의 유효기간과 쿠키의 유효기간이 서로 sync가 안 맞을 수도 있지 않을까요?

2023-05-08 08:38 UTC, Gorani9 requested changes
main 브랜치 rebase 해서 conflict 해결해주세요 ~

2023-05-15 06:23 UTC, yangchanhk98 commented on src/main/kotlin/com/wafflestudio/nostalgia/domain/user/model/User.kt
> +    var refreshToken: String? = null,
재발급 코드를 작성해서 이제야 올렸네요. 확인부탁드립니다!

2023-05-15 06:24 UTC, yangchanhk98 commented on src/main/kotlin/com/wafflestudio/nostalgia/domain/user/service/AuthTokenService.kt
> +@Transactional(readOnly = true)
정확히 필요할 지 잘 몰라서 어노테이션을 붙여 놓았는데요. 현재 필요 없으면 삭제하는 것이 나을까요?

2023-05-15 06:44 UTC, yangchanhk98 commented on src/main/kotlin/com/wafflestudio/nostalgia/domain/user/service/AuthTokenService.kt
> +    }
토큰 타입에 따라 만료기한만 차이가 나도록 메소드 병합했습니다!

2023-05-15 06:45 UTC, yangchanhk98 commented on src/main/kotlin/com/wafflestudio/nostalgia/domain/user/service/AuthTokenService.kt
> +            .maxAge(3600)
maxAge 유효기간 변경했습니다!

2023-05-30 06:49 UTC, Jhvictor4 commented on src/main/kotlin/com/wafflestudio/ggzz/domain/user/service/UserService.kt
>      @Transactional
안녕하세요, 중요하지는 않은데 지나가다가 코멘트 하나만 남겨보아요...

메소드에 정의한 `@Transactional` 어노테이션이 클래스 레벨에 있는 `@Transactional(readOnly = true)` 옵션을 덮어써서 사실상 무의미한 역할을 하고 있는 것 같습니다. 회원가입 메소드를 제외한 다른 메소드들의 @Transactional 어노테이션을 지우거나, 클래스 레벨의 어노테이션을 지우면 어떨까요?

런타임 에러는 없지만 이렇게 사용하게 되면 실제로 DB에 readonly transaction이 걸리지 않을 거라서용 ,,

2023-05-30 10:55 UTC, Gorani9 commented on src/main/kotlin/com/wafflestudio/ggzz/domain/user/service/UserService.kt
>      @Transactional
안녕하세요 이 부분은 제가 작성한 것인데요, 지혁님 말씀이 타당합니다.

나중에 메소드를 추가하면서 트랜잭션 거는 걸 잊었을 때 readonly 트랜잭션에서 write 연산으로 exception이 발생하여 문제를 빠르게 파악할 수 있다는 이유로 저는 보통 `@Transactional(readonly = true)` 를 거의 습관적으로 사용하게 되네요 😅. 서비스 안에 readonly 메소드가 섞여 있을 때 깔끔함은 덤이구요.

저는 잘 몰라서 여쭤보는데, 안티 패턴일까요?

2023-06-02 13:03 UTC, Jhvictor4 commented on src/main/kotlin/com/wafflestudio/ggzz/domain/user/service/UserService.kt
>      @Transactional
안티 패턴은 아닌 것 같아요 ㅎㅎ 쓰기 나름이니까요!
말씀하신 것을 보니 의도대로 쓰신 것 같아 그냥 넘어가면 될 것 같긴 한데.. ㅎㅎ

나중에 서비스가 커지거나 트래픽이 늘었을 떄, 트랜잭션이 거대해지면 디비에 부하를 줄 수도 있을 것 같아요.
또 트랜잭션 propagation 기본 설정이 상위 프록시의 트랜잭션을 그대로 쓰도록 되어있기 때문에, 롤백이나 커밋 제어가 (앱이 좀 더 복잡해지는 시기가 오면) 까다로워질 수도 있긴 해요!

2023-06-04 02:23 UTC, Gorani9 commented on src/main/kotlin/com/wafflestudio/ggzz/domain/user/service/UserService.kt
>      @Transactional
좋은 말씀 감사합니다 ㅎㅎ
참고할게요!

2023-06-04 06:26 UTC, Goraniieee commented on src/main/kotlin/com/wafflestudio/ggzz/global/config/SecurityConfig.kt
> +        }
SecurityFilterChain 에서 이미 해당 엔드포인트들은 permitAll로 되어 있는 상태인데,
customizer를 추가하신 이유가 있나요?

2023-06-04 06:26 UTC, Goraniieee commented on src/main/kotlin/com/wafflestudio/ggzz/global/config/SecurityConfig.kt
> +            .anyRequest().authenticated()
이것도 anyRequest로 바꾸신 이유가 있을까요?

2023-06-04 06:26 UTC, Goraniieee commented on src/main/kotlin/com/wafflestudio/ggzz/domain/user/model/User.kt
> +    var refreshToken: String? = null,
refresh 토큰을 DB에 저장하려는 이유가 있을까요?

2023-06-04 06:26 UTC, Goraniieee commented on src/main/kotlin/com/wafflestudio/ggzz/global/config/WebConfig.kt
> +class WebConfig(
이제 인터셉터 파일은 지워도 되지 않나요?

2023-06-04 06:26 UTC, Goraniieee commented on src/main/kotlin/com/wafflestudio/ggzz/global/config/SecurityConfig.kt
>      @Bean
이제 더 이상 세션을 사용하지 않아서 sessionManagement도 바꿔야 될 것 같습니다

2023-07-03 10:51 UTC, YeonghyeonKO commented on .github/workflows/gradle-ci.yml
요건 이미 main 브랜치에 있는 내용인데 기존 commit들이 반영이 안된 상황인가보군요 ㅎㅎ

2023-07-03 10:51 UTC, YeonghyeonKO commented on Dockerfile
> +CMD ["--spring.profiles.active=dev"]
엇 요건 필요한 내용인데 추가 감사합니다!

2023-07-03 10:51 UTC, YeonghyeonKO commented on src/main/kotlin/com/wafflestudio/ggzz/domain/user/controller/UserController.kt
> +        return userService.refresh(cookie)
client 입장에서 refresh API는 언제 사용하게되나요? client 단에서 알아서 요청하는 것이 의도인가요?

2023-07-03 10:51 UTC, YeonghyeonKO commented on src/main/kotlin/com/wafflestudio/ggzz/domain/user/model/User.kt
> +    var refreshToken: String? = null,
궁금하네요 ㅎㅎ 참고로 제 PR에서는 firebaseId가 DB에 저장되는데, 이는 firebaseToken을 firebase로 변환/검증하는 로직을 필요로합니다.

2023-07-06 14:26 UTC, yangchanhk98 commented on src/main/kotlin/com/wafflestudio/ggzz/global/config/SecurityConfig.kt
> +        }
Insomnia 통해서 해 본 결과 일단은 이 Customizer를 추가 하는 경우에만 해당 whitelist 들을 제대로 넘겨주고 있어서 추가할 수 밖에 없었습니다..!

2023-07-06 14:31 UTC, yangchanhk98 commented on src/main/kotlin/com/wafflestudio/ggzz/global/config/SecurityConfig.kt
> +            .anyRequest().authenticated()
이 파트는 permitAll한 request 제외, 다른 모든 request들에 대해서 인증이 필요하기에 바꾸기 전과 별 차이는 없긴 합니다.

2023-07-06 14:32 UTC, yangchanhk98 commented on src/main/kotlin/com/wafflestudio/ggzz/domain/user/model/User.kt
> +    var refreshToken: String? = null,
우선은 refresh 토큰을 DB에 저장하고 나중에 redis 등 이용하도록 바꿔야 할 것 같습니다.

2023-07-06 14:32 UTC, yangchanhk98 commented on src/main/kotlin/com/wafflestudio/ggzz/global/config/WebConfig.kt
> +class WebConfig(
넵 지우도록 하겠습니다!

2023-07-06 14:36 UTC, yangchanhk98 commented on src/main/kotlin/com/wafflestudio/ggzz/global/config/SecurityConfig.kt
> +        }
이 문제는 backend 회의 때 이야기하겠습니다!

2023-07-06 14:36 UTC, yangchanhk98 commented on src/main/kotlin/com/wafflestudio/ggzz/global/config/SecurityConfig.kt
>      @Bean
네 바로 바꾸겠습니다

2023-07-06 14:38 UTC, yangchanhk98 commented on .github/workflows/gradle-ci.yml
네 맞춰서 반영하겠습니다..!

2023-07-06 14:39 UTC, yangchanhk98 commented on src/main/kotlin/com/wafflestudio/ggzz/domain/user/controller/UserController.kt
> +        return userService.refresh(cookie)
네, 우선은 client에서 다시 refreshtoken을 cookie로 보내도록 요청하는 것이 의도입니다

2023-07-16 01:15 UTC, Goraniieee approved these changes

2023-07-16 01:20 UTC, merged